<H1>This notebook will be mainly used for the capstone project</H1>

In [1]:
#this notebook will be mainly used for the capstone project

import pandas as pd #import Pandas
import numpy as np #import Numpy

In [2]:
print("Hello Capstone Project Course!")

Hello Capstone Project Course!

In [ ]:
path = '/Data-Collisions.csv'
df_init = pd.read_csv(path)
#df_init.head()

In [6]:
df = df_init[['X','Y','STATUS','ADDRTYPE','LOCATION','SEVERITYCODE','SEVERITYDESC','COLLISIONTYPE','PERSONCOUNT','PEDCOUNT','PEDCYLCOUNT','VEHCOUNT','INCDTTM','JUNCTIONTYPE','SDOT_COLDESC','WEATHER','ROADCOND','LIGHTCOND','ST_COLDESC','HITPARKEDCAR']]
df.head()

,X,Y,STATUS,ADDRTYPE,LOCATION,SEVERITYCODE,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,PEDCYLCOUNT,VEHCOUNT,INCDTTM,JUNCTIONTYPE,SDOT_COLDESC,WEATHER,ROADCOND,LIGHTCOND,ST_COLDESC,HITPARKEDCAR
0,-122.323148,47.703140,Matched,Intersection,5TH AVE NE AND NE 103RD ST,2,Injury Collision,Angles,2,0,0,2,3/27/2013 2:54:00 PM,At Intersection (intersection related),"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",Overcast,Wet,Daylight,Entering at angle,N
1,-122.347294,47.647172,Matched,Block,AURORA BR BETWEEN RAYE ST AND BRIDGE WAY N,1,Property Damage Only Collision,Sideswipe,2,0,0,2,12/20/2006 6:55:00 PM,Mid-Block (not related to intersection),"MOTOR VEHICLE STRUCK MOTOR VEHICLE, LEFT SIDE ...",Raining,Wet,Dark - Street Lights On,From same direction - both going straight - bo...,N
2,-122.334540,47.607871,Matched,Block,4TH AVE BETWEEN SENECA ST AND UNIVERSITY ST,1,Property Damage Only Collision,Parked Car,4,0,0,3,11/18/2004 10:20:00 AM,Mid-Block (not related to intersection),"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",Overcast,Dry,Daylight,One parked--one moving,N
3,-122.334803,47.604803,Matched,Block,2ND AVE BETWEEN MARION ST AND MADISON ST,1,Property Damage Only Collision,Other,3,0,0,3,3/29/2013 9:26:00 AM,Mid-Block (not related to intersection),"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",Clear,Dry,Daylight,From same direction - all others,N
4,-122.306426,47.545739,Matched,Intersection,SWIFT AVE S AND SWIFT AV OFF RP,2,Injury Collision,Angles,2,0,0,2,1/28/2004 8:04:00 AM,At Intersection (intersection related),"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",Raining,Wet,Daylight,Entering at angle,N

In [8]:
df[['VEHCOUNT','PERSONCOUNT','SEVERITYCODE']].describe()

            VEHCOUNT    PERSONCOUNT   SEVERITYCODE
count  194673.000000  194673.000000  194673.000000
mean        1.920780       2.444427       1.298901
std         0.631047       1.345929       0.457778
min         0.000000       0.000000       1.000000
25%         2.000000       2.000000       1.000000
50%         2.000000       2.000000       1.000000
75%         2.000000       3.000000       2.000000
max        12.000000      81.000000       2.000000